import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        outline: "var(--color-outline)",
        "on-error-container": "var(--color-on-error-container)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "on-secondary": "var(--color-on-secondary)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        error: "var(--color-error)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "outline-variant": "var(--color-outline-variant)",
        primary: "var(--color-primary)",
        "on-background": "var(--color-on-background)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-dim": "var(--color-surface-dim)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-tertiary": "var(--color-on-tertiary)",
        "surface-variant": "var(--color-surface-variant)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-container": "var(--color-surface-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-primary": "var(--color-inverse-primary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        background: "var(--color-background)",
        tertiary: "var(--color-tertiary)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        surface: "var(--color-surface)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "primary-container": "var(--color-primary-container)",
        secondary: "var(--color-secondary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "secondary-container": "var(--color-secondary-container)",
        "error-container": "var(--color-error-container)",
        "on-error": "var(--color-on-error)",
        "on-primary": "var(--color-on-primary)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        "margin-desktop": "32px",
        xs: "4px",
        lg: "24px",
        base: "4px",
        "2xl": "48px",
        gutter: "16px",
        md: "16px",
        sm: "8px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        caption: ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "40px",
          { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
      animation: {
        "marker-pulse": "marker-pulse 2s infinite",
      },
      keyframes: {
        "marker-pulse": {
          "0%": {
            transform: "scale(1)",
            boxShadow: "0 0 0 0 rgba(255, 107, 53, 0.7)",
          },
          "70%": {
            transform: "scale(1.1)",
            boxShadow: "0 0 0 10px rgba(255, 107, 53, 0)",
          },
          "100%": {
            transform: "scale(1)",
            boxShadow: "0 0 0 0 rgba(255, 107, 53, 0)",
          },
        },
      },
    },
  },
  plugins: [],
};
export default config;
