apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-demo
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.feishu: ""
    notifications.argoproj.io/subscribe.on-sync-failed.feishu: ""
    notifications.argoproj.io/subscribe.on-health-degraded.feishu: ""
spec:
  project: dev-apps
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://2529FEDC225DA96D7F3A93A1C7ACD4D4.gr7.eu-central-1.eks.amazonaws.com
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
